#!/usr/bin/python
import json
import urllib2

#################################################################################

# CONSTANTS
# Edit these values to change the results!!

ARTIST = 'The Lumineers'

###############################################################################


url = 'http://lyrics.wikia.com/api.php?artist='
artist = ARTIST.replace(' ', '+')
url = url + artist
url = url + '&fmt=json'

data = json.load(urllib2.urlopen(url))

print url
